# Azure DevOps pipeline to build, check source codes and run tests.
#
# To make Danger JS run on a pull request you need to add the following pipeline
# variable and set it with a GitHub access token (scope public_repo); otherwise
# set its value to 'skip' without marking it secret:
# - DANGER_GITHUB_API_TOKEN
#

variables:
  NODE_VERSION: '18.17.1'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

# Automatically triggered on PR
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pr-trigger
trigger:
  branches:
    include:
    - main
    - develop

# Execute agents (jobs) on latest Ubuntu version.
# To change OS for a specific, ovverride "pool" attribute inside the job definition
pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v19
      endpoint: 'io-azure-devops-github-ro'

    - repository: checkout-be-mock
      type: github
      name: pagopa/pagopa-checkout-be-mock
      ref: CHK-4119-implements-outcome-info-api
      endpoint: 'io-azure-devops-github-ro'

stages:
  - stage: Build
    dependsOn: []
    jobs:
      - job: make_build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - template: templates/node-job-setup/template.yaml@pagopaCommons

        - template: azure-templates/setup-env.yml
          parameters:
            env: 'DEV'
            api_timeout: 10000
            api_host: 'http://localhost:1234'
            checkout_api_path: "/ecommerce/checkout/v1"
            checkout_api_v2_path: "/ecommerce/checkout/v2"
            io_api_v2_path: "/ecommerce/webview/v2"
            npg_sdk_url: 'https://stg-ta.nexigroup.com/monetaweb/resources/hfsdk.js'
            gdi_check_timeout: 12000
            io_client_redirect_outcome_path: 'https://api.dev.platform.pagopa.it/ecommerce/io-outcomes/v1/transactions'
            checkout_client_redirect_outcome_path: 'https://dev.checkout.pagopa.it/v2/esito'
            show_continue_io_btn_delay_millis: 2000

        - script: |
            yarn build
          displayName: 'Build'

  - stage: Static_Analysis
    dependsOn: []
    jobs:
      - job: lint
        steps:
        - template: templates/node-job-setup/template.yaml@pagopaCommons
        - script: yarn lint
          displayName: 'Lint'
      - job: danger
        condition:
          and(
            succeeded(),
            ne(variables['DANGER_GITHUB_API_TOKEN'], 'skip')
          )
        steps:
          - template: templates/node-job-setup/template.yaml@pagopaCommons

          - bash: yarn danger ci
            env:
              DANGER_GITHUB_API_TOKEN: '$(DANGER_GITHUB_API_TOKEN)'
            displayName: 'Danger CI'

  # B) Run unit tests if there is a push or pull request on any branch.
  - stage: Unit_Tests
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: []
    jobs:
      - job: run_unit_tests
        steps:
        - template: templates/node-job-setup/template.yaml@pagopaCommons

        - task: SonarCloudPrepare@3
          displayName: 'Prepare SonarCloud analysis configuration'
          inputs:
            SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
            organization: '$(SONARCLOUD_ORG)'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: $(SONARCLOUD_PROJECT_KEY)
            cliProjectName: $(SONARCLOUD_PROJECT_NAME)
            cliSources: '.'
            extraProperties: |
              sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
              sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
              sonar.javascript.lcov.reportPaths=coverage/lcov.info
              sonar.clover.reportPath=coverage/clover.xml
              sonar.testExecutionReportPaths=test-report.xml
              sonar.sourceEncoding=UTF-8
              sonar.sources=src/
              sonar.exclusions=src/**/__tests__/**/*,src/**/__test__/**,**/*.js,src/**/index.ts,src/**/__mocks__/**/*,/src/utils/testing/**,/src/__integration_tests__/**
              sonar.tests=src
              sonar.test.inclusions=src/**/__tests__/**/*,src/**/__test__/**
              sonar.cpd.exclusions=src/**/__tests__/**,src/**/__test__/**,__mocks__/**,/src/utils/testing/**

        - script: yarn generate
          displayName: 'Generate definitions'

        - script: yarn test:coverage
          displayName: 'Unit tests exec'

        - task: SonarCloudAnalyze@3
          displayName: 'Run SonarCloud analysis'
          
        - task: SonarCloudPublish@3
          displayName: 'Publish SonarCloud results on build summary'
          inputs:
            pollingTimeoutSec: '300' 
        - task: PublishTestResults@2
          displayName: 'Publish test results from Jest tests'
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/*TEST.xml' 
            searchFolder: '$(System.DefaultWorkingDirectory)'
            failTaskOnFailedTests: true

        - task: PublishCodeCoverageResults@2
          displayName: 'Publish code coverage from Jest tests'
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: 'coverage/clover.xml'

# B) Run integration tests if there is a push or pull request on any branch.
  - stage: Integration_Tests
    pool:
      vmImage: 'ubuntu-22.04'
    dependsOn: []
    jobs:
      - job: run_integration_tests
        timeoutInMinutes: 30
        steps:

        - checkout: checkout-be-mock

        - script: |
            cp env.example .env
            sed -i "s/^NPG_API_KEY=.*$/NPG_API_KEY=$(CHECKOUT-TEST-NPG-API-KEY)/" .env
            sed -i "s/^PSP_API_KEY=.*$/PSP_API_KEY=$(CHECKOUT-TEST-NPG-API-KEY)/" .env
          workingDirectory: pagopa-checkout-be-mock
          displayName: 'Setup env for mock'

        - script: yarn global add node-gyp && yarn install && yarn build
          workingDirectory: pagopa-checkout-be-mock
          displayName: 'Setup deps for mock'

        - script: |
            nohup yarn start &
          displayName: 'Start backend mock'
          workingDirectory: pagopa-checkout-be-mock

        - checkout: self

        - template: templates/node-job-setup/template.yaml@pagopaCommons
          parameters:
           projectDir: pagopa-ecommerce-fe

        - script: |
            export $(grep -v '^#' .env.development | xargs)
          displayName: 'export envs from .env.development'
          workingDirectory: pagopa-ecommerce-fe

        - script: |
            yarn start-io-mock &
          displayName: 'Start ecommerce fe IO mock'
          workingDirectory: pagopa-ecommerce-fe

        - script: |
            yarn dev &
          displayName: 'Start ecommerce fe'
          workingDirectory: pagopa-ecommerce-fe

        - script: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:1234)" != "200" ]]; do sleep 5; done
          displayName: 'Wait for backend to be up and running'
          workingDirectory: pagopa-ecommerce-fe

        - script: yarn test:integration
          displayName: 'Integration tests exec'
          workingDirectory: pagopa-ecommerce-fe
          
        - script: |
            yarn dev:env:noredirect &
          displayName: 'Set ecommerce fe with noredirect env'
          workingDirectory: pagopa-ecommerce-fe

        - script: yarn test:noredirect
          displayName: 'IO noredirect button Integration tests exec'
          workingDirectory: pagopa-ecommerce-fe

        - task: PublishTestResults@2
          displayName: 'Publish integration tests results from Jest tests'
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/*TEST.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)'
            failTaskOnFailedTests: true
