# Azure DevOps pipeline template used to build bundle.
parameters:
  - name: 'env'
    type: string
    default: ''

  - name: 'api_timeout'
    type: number
    default: 10000

  - name: 'api_host'
    type: string
    default: ''

  - name: 'checkout_api_path'
    type: string
    default: ''

  - name: "checkout_api_v2_path"
    type: string
    default: ""

  - name: 'io_api_v1_path'
    type: string
    default: ''

  - name: 'npg_sdk_url'
    type: string
    default: ''
  
  - name: 'gdi_check_timeout'
    type: number
    default: 12000

  - name: 'io_client_redirect_outcome_path'
    type: string
    default: ''

  - name: 'checkout_client_redirect_outcome_path'
    type: string
    default: ' '

  - name: 'show_continue_io_btn_delay_millis'
    type: number
    default: 2000

steps:
- bash: |
    chmod +x env.sh
    env -i \
      ECOMMERCE_ENV=${{ parameters.env }} \
      ECOMMERCE_API_TIMEOUT=${{ parameters.api_timeout }} \
      ECOMMERCE_API_HOST=${{ parameters.api_host }} \
      ECOMMERCE_CHECKOUT_API_PATH=${{ parameters.checkout_api_path }} \
      ECOMMERCE_CHECKOUT_API_V2_PATH=${{ parameters.checkout_api_v2_path }} \
      ECOMMERCE_IO_API_V1_PATH=${{ parameters.io_api_v1_path }} \
      ECOMMERCE_GDI_CHECK_TIMEOUT=${{ parameters.gdi_check_timeout }} \
      ECOMMERCE_NPG_SDK_URL=${{ parameters.npg_sdk_url }} \
      ECOMMERCE_IO_CLIENT_REDIRECT_OUTCOME_PATH=${{ parameters.io_client_redirect_outcome_path }} \
      ECOMMERCE_CHECKOUT_CLIENT_REDIRECT_OUTCOME_PATH=${{ parameters.checkout_client_redirect_outcome_path }} \
      ECOMMERCE_SHOW_CONTINUE_IO_BTN_DELAY_MILLIS=${{ parameters.show_continue_io_btn_delay_millis }} \
      bash env.sh

  displayName: 'Populate environment file'
